export type CityRegion =
  | "north"
  | "south"
  | "east"
  | "west"
  | "central"
  | "northeast";

export interface CityInfo {
  slug: string;
  name: string;
  nameHi: string;
  state: string;
  stateHi: string;
  region: CityRegion;
  /** ISO 639-1 codes — primary regional languages spoken at home / in pujas */
  languages: string[];
  /** Multiplier on indicative puja price; 1.0 = base */
  priceMultiplier: number;
  /** Approximate count of verified pandits we serve in the city */
  panditCount: number;
  /** One landmark temple or river ghat used in city blurb */
  landmark: string;
  landmarkHi: string;
  /** Whether the city is a major tirth / pilgrimage hub */
  isTirth?: boolean;
  /** Short USP line shown on landing pages */
  blurb: string;
  blurbHi: string;
}

export const CITIES: CityInfo[] = [
  // ---- Tirth / pilgrimage hubs (high-intent SEO) ----
  { slug: "varanasi", name: "Varanasi", nameHi: "वाराणसी", state: "Uttar Pradesh", stateHi: "उत्तर प्रदेश", region: "north", languages: ["hi", "sa"], priceMultiplier: 0.95, panditCount: 180, landmark: "Kashi Vishwanath", landmarkHi: "काशी विश्वनाथ", isTirth: true, blurb: "Pujas at the ghats of Kashi performed by hereditary Banarasi pandits.", blurbHi: "काशी के घाटों पर वंश-परंपरागत बनारसी पंडितों द्वारा सम्पन्न पूजा।" },
  { slug: "haridwar", name: "Haridwar", nameHi: "हरिद्वार", state: "Uttarakhand", stateHi: "उत्तराखंड", region: "north", languages: ["hi", "sa"], priceMultiplier: 0.95, panditCount: 95, landmark: "Har Ki Pauri", landmarkHi: "हर की पौड़ी", isTirth: true, blurb: "Ganga-aarti aligned pujas with sankalp at Har Ki Pauri.", blurbHi: "हर की पौड़ी पर संकल्प सहित गंगा आरती अनुरूप पूजा।" },
  { slug: "rishikesh", name: "Rishikesh", nameHi: "ऋषिकेश", state: "Uttarakhand", stateHi: "उत्तराखंड", region: "north", languages: ["hi", "sa"], priceMultiplier: 0.95, panditCount: 70, landmark: "Triveni Ghat", landmarkHi: "त्रिवेणी घाट", isTirth: true, blurb: "Ashram-trained Vedic acharyas conduct pujas at Triveni Ghat.", blurbHi: "त्रिवेणी घाट पर आश्रम-प्रशिक्षित वैदिक आचार्यों द्वारा पूजा।" },
  { slug: "ujjain", name: "Ujjain", nameHi: "उज्जैन", state: "Madhya Pradesh", stateHi: "मध्य प्रदेश", region: "central", languages: ["hi", "sa"], priceMultiplier: 0.9, panditCount: 85, landmark: "Mahakaleshwar Jyotirlinga", landmarkHi: "महाकालेश्वर ज्योतिर्लिंग", isTirth: true, blurb: "Mahakal-tradition pandits for Rudrabhishek and Kaal Sarp pujas.", blurbHi: "रुद्राभिषेक एवं कालसर्प पूजा हेतु महाकाल परंपरा के पंडित।" },
  { slug: "mathura", name: "Mathura", nameHi: "मथुरा", state: "Uttar Pradesh", stateHi: "उत्तर प्रदेश", region: "north", languages: ["hi", "sa"], priceMultiplier: 0.9, panditCount: 60, landmark: "Krishna Janmabhoomi", landmarkHi: "कृष्ण जन्मभूमि", isTirth: true, blurb: "Vaishnav pandits from Krishna Janmabhoomi parampara.", blurbHi: "कृष्ण जन्मभूमि परंपरा के वैष्णव पंडित।" },
  { slug: "vrindavan", name: "Vrindavan", nameHi: "वृन्दावन", state: "Uttar Pradesh", stateHi: "उत्तर प्रदेश", region: "north", languages: ["hi", "sa"], priceMultiplier: 0.9, panditCount: 55, landmark: "Banke Bihari Mandir", landmarkHi: "बांके बिहारी मंदिर", isTirth: true, blurb: "Goswami-lineage pandits for Vaishnav pujas in Vrindavan.", blurbHi: "वृन्दावन में वैष्णव पूजाओं हेतु गोस्वामी वंश के पंडित।" },
  { slug: "tirupati", name: "Tirupati", nameHi: "तिरुपति", state: "Andhra Pradesh", stateHi: "आंध्र प्रदेश", region: "south", languages: ["te", "ta", "sa"], priceMultiplier: 1.05, panditCount: 70, landmark: "Tirumala Venkateswara", landmarkHi: "तिरुमला वेंकटेश्वर", isTirth: true, blurb: "Vaikhanasa-tradition Archakas serving Tirumala devotees.", blurbHi: "तिरुमला भक्तों की सेवा हेतु वैखानस परंपरा के अर्चक।" },
  { slug: "gaya", name: "Gaya", nameHi: "गया", state: "Bihar", stateHi: "बिहार", region: "east", languages: ["hi", "sa"], priceMultiplier: 0.85, panditCount: 110, landmark: "Vishnupad Mandir", landmarkHi: "विष्णुपद मंदिर", isTirth: true, blurb: "Verified Gayawal pandits for Pind Daan and ancestral pujas.", blurbHi: "पिंड दान एवं पितृ पूजा हेतु सत्यापित गयावाल पंडित।" },
  { slug: "ayodhya", name: "Ayodhya", nameHi: "अयोध्या", state: "Uttar Pradesh", stateHi: "उत्तर प्रदेश", region: "north", languages: ["hi", "sa"], priceMultiplier: 0.95, panditCount: 75, landmark: "Ram Janmabhoomi", landmarkHi: "राम जन्मभूमि", isTirth: true, blurb: "Ram-bhakti tradition pandits at the Saryu ghats of Ayodhya.", blurbHi: "अयोध्या के सरयू घाटों पर राम भक्ति परंपरा के पंडित।" },
  { slug: "puri", name: "Puri", nameHi: "पुरी", state: "Odisha", stateHi: "ओडिशा", region: "east", languages: ["bn", "hi", "sa"], priceMultiplier: 0.9, panditCount: 50, landmark: "Jagannath Temple", landmarkHi: "जगन्नाथ मंदिर", isTirth: true, blurb: "Jagannath-parampara Sevayats for pujas in Shri Kshetra.", blurbHi: "श्री क्षेत्र में जगन्नाथ परंपरा के सेवायत द्वारा पूजा।" },
  { slug: "dwarka", name: "Dwarka", nameHi: "द्वारका", state: "Gujarat", stateHi: "गुजरात", region: "west", languages: ["gu", "hi", "sa"], priceMultiplier: 0.95, panditCount: 40, landmark: "Dwarkadhish Temple", landmarkHi: "द्वारकाधीश मंदिर", isTirth: true, blurb: "Pushti-marg pandits for Krishna pujas in Dwarka Puri.", blurbHi: "द्वारका पुरी में कृष्ण पूजा हेतु पुष्टिमार्ग के पंडित।" },
  { slug: "prayagraj", name: "Prayagraj", nameHi: "प्रयागराज", state: "Uttar Pradesh", stateHi: "उत्तर प्रदेश", region: "north", languages: ["hi", "sa"], priceMultiplier: 0.9, panditCount: 95, landmark: "Triveni Sangam", landmarkHi: "त्रिवेणी संगम", isTirth: true, blurb: "Tirth-purohits at the Triveni Sangam for ancestral and shanti pujas.", blurbHi: "त्रिवेणी संगम पर पितृ एवं शांति पूजा हेतु तीर्थ-पुरोहित।" },
  { slug: "amritsar", name: "Amritsar", nameHi: "अमृतसर", state: "Punjab", stateHi: "पंजाब", region: "north", languages: ["hi"], priceMultiplier: 1.0, panditCount: 35, landmark: "Durgiana Mandir", landmarkHi: "दुर्गियाना मंदिर", blurb: "Punjabi Vedic pandits serving the Durgiana parikrama.", blurbHi: "दुर्गियाना परिक्रमा क्षेत्र में सेवारत पंजाबी वैदिक पंडित।" },
  { slug: "kanchipuram", name: "Kanchipuram", nameHi: "कांचीपुरम", state: "Tamil Nadu", stateHi: "तमिलनाडु", region: "south", languages: ["ta", "sa"], priceMultiplier: 1.0, panditCount: 45, landmark: "Kamakshi Amman", landmarkHi: "कामाक्षी अम्मन", isTirth: true, blurb: "Adi-shankara parampara Vadhyars for Devi and Shiva pujas.", blurbHi: "देवी एवं शिव पूजा हेतु आदि शंकर परंपरा के वाध्यार।" },
  { slug: "madurai", name: "Madurai", nameHi: "मदुरै", state: "Tamil Nadu", stateHi: "तमिलनाडु", region: "south", languages: ["ta", "sa"], priceMultiplier: 1.0, panditCount: 40, landmark: "Meenakshi Amman", landmarkHi: "मीनाक्षी अम्मन", isTirth: true, blurb: "Meenakshi-temple parampara Bhattars for Shakta pujas.", blurbHi: "शाक्त पूजा हेतु मीनाक्षी मंदिर परंपरा के भट्टार।" },
  { slug: "pushkar", name: "Pushkar", nameHi: "पुष्कर", state: "Rajasthan", stateHi: "राजस्थान", region: "north", languages: ["hi", "sa"], priceMultiplier: 0.9, panditCount: 35, landmark: "Brahma Mandir", landmarkHi: "ब्रह्मा मंदिर", isTirth: true, blurb: "Pushkar-ghat Brahman purohits for sankalp pujas.", blurbHi: "संकल्प पूजा हेतु पुष्कर घाट के ब्राह्मण पुरोहित।" },

  // ---- Tier 1 metros ----
  { slug: "mumbai", name: "Mumbai", nameHi: "मुंबई", state: "Maharashtra", stateHi: "महाराष्ट्र", region: "west", languages: ["mr", "hi"], priceMultiplier: 1.35, panditCount: 220, landmark: "Siddhivinayak Mandir", landmarkHi: "सिद्धिविनायक मंदिर", blurb: "On-time pandits across Mumbai's western and central suburbs.", blurbHi: "मुंबई के पश्चिमी एवं मध्य उपनगरों में समय पर पहुँचने वाले पंडित।" },
  { slug: "delhi", name: "Delhi", nameHi: "दिल्ली", state: "Delhi", stateHi: "दिल्ली", region: "north", languages: ["hi"], priceMultiplier: 1.25, panditCount: 240, landmark: "Chhatarpur Mandir", landmarkHi: "छतरपुर मंदिर", blurb: "Pandits across Delhi NCR serving from South Delhi to Dwarka.", blurbHi: "दक्षिण दिल्ली से द्वारका तक पूरे दिल्ली NCR में सेवारत पंडित।" },
  { slug: "bengaluru", name: "Bengaluru", nameHi: "बेंगलुरु", state: "Karnataka", stateHi: "कर्नाटक", region: "south", languages: ["hi", "ta", "te"], priceMultiplier: 1.3, panditCount: 200, landmark: "ISKCON Bengaluru", landmarkHi: "इस्कॉन बेंगलुरु", blurb: "North-Indian and South-Indian Vedic pandits across Bengaluru.", blurbHi: "बेंगलुरु में उत्तर एवं दक्षिण भारतीय वैदिक पंडित।" },
  { slug: "hyderabad", name: "Hyderabad", nameHi: "हैदराबाद", state: "Telangana", stateHi: "तेलंगाना", region: "south", languages: ["te", "hi", "sa"], priceMultiplier: 1.2, panditCount: 160, landmark: "Birla Mandir", landmarkHi: "बिड़ला मंदिर", blurb: "Smartha and Vaishnav pandits across HiTec City and old Hyderabad.", blurbHi: "हाईटेक सिटी एवं पुराने हैदराबाद में स्मार्त और वैष्णव पंडित।" },
  { slug: "chennai", name: "Chennai", nameHi: "चेन्नई", state: "Tamil Nadu", stateHi: "तमिलनाडु", region: "south", languages: ["ta", "sa"], priceMultiplier: 1.2, panditCount: 170, landmark: "Kapaleeshwarar Temple", landmarkHi: "कपालीश्वर मंदिर", blurb: "Iyer and Iyengar Vadhyars across Chennai's IT and traditional belts.", blurbHi: "चेन्नई के आईटी एवं पारंपरिक क्षेत्रों में अय्यर और अयंगर वाध्यार।" },
  { slug: "kolkata", name: "Kolkata", nameHi: "कोलकाता", state: "West Bengal", stateHi: "पश्चिम बंगाल", region: "east", languages: ["bn", "hi", "sa"], priceMultiplier: 1.1, panditCount: 150, landmark: "Dakshineswar Kali", landmarkHi: "दक्षिणेश्वर काली", blurb: "Bengali Brahman purohits for Shakta and Vaishnav pujas.", blurbHi: "शाक्त एवं वैष्णव पूजा हेतु बंगाली ब्राह्मण पुरोहित।" },
  { slug: "pune", name: "Pune", nameHi: "पुणे", state: "Maharashtra", stateHi: "महाराष्ट्र", region: "west", languages: ["mr", "hi", "sa"], priceMultiplier: 1.2, panditCount: 140, landmark: "Dagdusheth Ganpati", landmarkHi: "दगडूशेठ गणपति", blurb: "Konkanastha and Deshastha pandits across Pune and PCMC.", blurbHi: "पुणे एवं PCMC में कोंकणस्थ एवं देशस्थ पंडित।" },
  { slug: "ahmedabad", name: "Ahmedabad", nameHi: "अहमदाबाद", state: "Gujarat", stateHi: "गुजरात", region: "west", languages: ["gu", "hi", "sa"], priceMultiplier: 1.1, panditCount: 130, landmark: "Jagannath Mandir Jamalpur", landmarkHi: "जगन्नाथ मंदिर जमालपुर", blurb: "Audichya and Mevada Brahmin pandits across Ahmedabad.", blurbHi: "अहमदाबाद में औदीच्य एवं मेवाड़ा ब्राह्मण पंडित।" },
  { slug: "jaipur", name: "Jaipur", nameHi: "जयपुर", state: "Rajasthan", stateHi: "राजस्थान", region: "north", languages: ["hi", "sa"], priceMultiplier: 1.05, panditCount: 110, landmark: "Govind Dev Ji Mandir", landmarkHi: "गोविंद देव जी मंदिर", blurb: "Pushkarna and Gaur Brahman pandits across Jaipur.", blurbHi: "जयपुर भर में पुष्करणा एवं गौड़ ब्राह्मण पंडित।" },
  { slug: "lucknow", name: "Lucknow", nameHi: "लखनऊ", state: "Uttar Pradesh", stateHi: "उत्तर प्रदेश", region: "north", languages: ["hi", "sa"], priceMultiplier: 1.0, panditCount: 95, landmark: "Hanuman Setu Mandir", landmarkHi: "हनुमान सेतु मंदिर", blurb: "Awadhi pandits with Sanskrit-school training across Lucknow.", blurbHi: "लखनऊ भर में संस्कृत-पाठशाला प्रशिक्षित अवधी पंडित।" },
  { slug: "kanpur", name: "Kanpur", nameHi: "कानपुर", state: "Uttar Pradesh", stateHi: "उत्तर प्रदेश", region: "north", languages: ["hi", "sa"], priceMultiplier: 0.95, panditCount: 80, landmark: "JK Temple", landmarkHi: "जे.के. मंदिर", blurb: "Verified pandits across Kanpur Nagar and Kanpur Dehat.", blurbHi: "कानपुर नगर एवं कानपुर देहात में सत्यापित पंडित।" },
  { slug: "nagpur", name: "Nagpur", nameHi: "नागपुर", state: "Maharashtra", stateHi: "महाराष्ट्र", region: "central", languages: ["mr", "hi"], priceMultiplier: 1.0, panditCount: 75, landmark: "Tekdi Ganesh Mandir", landmarkHi: "टेकड़ी गणेश मंदिर", blurb: "Marathi and Hindi-fluent pandits across Nagpur.", blurbHi: "नागपुर भर में मराठी एवं हिंदी में निपुण पंडित।" },
  { slug: "indore", name: "Indore", nameHi: "इंदौर", state: "Madhya Pradesh", stateHi: "मध्य प्रदेश", region: "central", languages: ["hi", "sa"], priceMultiplier: 1.0, panditCount: 85, landmark: "Khajrana Ganesh", landmarkHi: "खजराना गणेश", blurb: "Malwa-region Brahman pandits across Indore.", blurbHi: "इंदौर भर में मालवा क्षेत्र के ब्राह्मण पंडित।" },
  { slug: "bhopal", name: "Bhopal", nameHi: "भोपाल", state: "Madhya Pradesh", stateHi: "मध्य प्रदेश", region: "central", languages: ["hi", "sa"], priceMultiplier: 0.95, panditCount: 70, landmark: "Birla Mandir", landmarkHi: "बिड़ला मंदिर", blurb: "Verified pandits across new and old Bhopal.", blurbHi: "नए एवं पुराने भोपाल में सत्यापित पंडित।" },
  { slug: "patna", name: "Patna", nameHi: "पटना", state: "Bihar", stateHi: "बिहार", region: "east", languages: ["hi", "sa"], priceMultiplier: 0.9, panditCount: 80, landmark: "Mahavir Mandir", landmarkHi: "महावीर मंदिर", blurb: "Maithil and Bhojpuri pandits across Patna.", blurbHi: "पटना भर में मैथिल एवं भोजपुरी पंडित।" },
  { slug: "vadodara", name: "Vadodara", nameHi: "वडोदरा", state: "Gujarat", stateHi: "गुजरात", region: "west", languages: ["gu", "hi", "sa"], priceMultiplier: 1.0, panditCount: 60, landmark: "EME Temple", landmarkHi: "ई.एम.ई. मंदिर", blurb: "Audichya pandits across Vadodara and surrounding talukas.", blurbHi: "वडोदरा एवं आसपास की तहसीलों में औदीच्य पंडित।" },
  { slug: "surat", name: "Surat", nameHi: "सूरत", state: "Gujarat", stateHi: "गुजरात", region: "west", languages: ["gu", "hi"], priceMultiplier: 1.05, panditCount: 75, landmark: "Ambaji Mandir", landmarkHi: "अंबाजी मंदिर", blurb: "Verified pandits across Surat's diamond and textile clusters.", blurbHi: "सूरत के हीरा एवं वस्त्र क्लस्टरों में सत्यापित पंडित।" },
  { slug: "ludhiana", name: "Ludhiana", nameHi: "लुधियाना", state: "Punjab", stateHi: "पंजाब", region: "north", languages: ["hi"], priceMultiplier: 1.05, panditCount: 50, landmark: "Mata Rani Mandir", landmarkHi: "माता रानी मंदिर", blurb: "Punjabi Vedic pandits across Ludhiana.", blurbHi: "लुधियाना भर में पंजाबी वैदिक पंडित।" },
  { slug: "agra", name: "Agra", nameHi: "आगरा", state: "Uttar Pradesh", stateHi: "उत्तर प्रदेश", region: "north", languages: ["hi", "sa"], priceMultiplier: 0.95, panditCount: 60, landmark: "Mankameshwar Mandir", landmarkHi: "मनकामेश्वर मंदिर", blurb: "Braj-region pandits across Agra and Mathura belt.", blurbHi: "आगरा एवं मथुरा क्षेत्र में ब्रज क्षेत्र के पंडित।" },
  { slug: "nashik", name: "Nashik", nameHi: "नाशिक", state: "Maharashtra", stateHi: "महाराष्ट्र", region: "west", languages: ["mr", "hi", "sa"], priceMultiplier: 1.0, panditCount: 70, landmark: "Trimbakeshwar Jyotirlinga", landmarkHi: "त्र्यंबकेश्वर ज्योतिर्लिंग", isTirth: true, blurb: "Trimbakeshwar parampara Brahman pandits across Nashik.", blurbHi: "नाशिक भर में त्र्यंबकेश्वर परंपरा के ब्राह्मण पंडित।" },
  { slug: "faridabad", name: "Faridabad", nameHi: "फरीदाबाद", state: "Haryana", stateHi: "हरियाणा", region: "north", languages: ["hi"], priceMultiplier: 1.15, panditCount: 65, landmark: "ISKCON Faridabad", landmarkHi: "इस्कॉन फरीदाबाद", blurb: "Delhi NCR pandits available across Faridabad sectors.", blurbHi: "फरीदाबाद के सभी सेक्टरों में दिल्ली NCR के पंडित उपलब्ध।" },
  { slug: "ghaziabad", name: "Ghaziabad", nameHi: "गाजियाबाद", state: "Uttar Pradesh", stateHi: "उत्तर प्रदेश", region: "north", languages: ["hi"], priceMultiplier: 1.15, panditCount: 70, landmark: "Dudheshwar Nath", landmarkHi: "दूधेश्वर नाथ", blurb: "Delhi NCR pandits across Indirapuram, Vaishali and Raj Nagar.", blurbHi: "इंदिरापुरम, वैशाली एवं राज नगर में दिल्ली NCR के पंडित।" },
  { slug: "coimbatore", name: "Coimbatore", nameHi: "कोयंबटूर", state: "Tamil Nadu", stateHi: "तमिलनाडु", region: "south", languages: ["ta", "sa"], priceMultiplier: 1.05, panditCount: 55, landmark: "Marudhamalai Murugan", landmarkHi: "मरुदामलाई मुरुगन", blurb: "Kongu-region Vadhyars across Coimbatore.", blurbHi: "कोयंबटूर भर में कोंगु क्षेत्र के वाध्यार।" },
  { slug: "visakhapatnam", name: "Visakhapatnam", nameHi: "विशाखापत्तनम", state: "Andhra Pradesh", stateHi: "आंध्र प्रदेश", region: "south", languages: ["te", "sa"], priceMultiplier: 1.0, panditCount: 50, landmark: "Simhachalam", landmarkHi: "सिंहाचलम", blurb: "Coastal Andhra pandits across Visakhapatnam.", blurbHi: "विशाखापत्तनम भर में तटीय आंध्र क्षेत्र के पंडित।" },
  { slug: "thane", name: "Thane", nameHi: "ठाणे", state: "Maharashtra", stateHi: "महाराष्ट्र", region: "west", languages: ["mr", "hi"], priceMultiplier: 1.3, panditCount: 90, landmark: "Kopineshwar Mandir", landmarkHi: "कोपिनेश्वर मंदिर", blurb: "MMR pandits across Thane, Mulund and Bhiwandi.", blurbHi: "ठाणे, मुलुंड एवं भिवंडी में MMR क्षेत्र के पंडित।" },
  { slug: "gurugram", name: "Gurugram", nameHi: "गुरुग्राम", state: "Haryana", stateHi: "हरियाणा", region: "north", languages: ["hi"], priceMultiplier: 1.3, panditCount: 90, landmark: "Sheetla Mata Mandir", landmarkHi: "शीतला माता मंदिर", blurb: "Delhi NCR pandits available across all Gurugram sectors and DLF.", blurbHi: "गुरुग्राम के सभी सेक्टरों एवं DLF में दिल्ली NCR के पंडित उपलब्ध।" },
  { slug: "noida", name: "Noida", nameHi: "नोएडा", state: "Uttar Pradesh", stateHi: "उत्तर प्रदेश", region: "north", languages: ["hi"], priceMultiplier: 1.3, panditCount: 95, landmark: "Kalibari Mandir Sec-26", landmarkHi: "कालीबाड़ी मंदिर सेक्टर-26", blurb: "Delhi NCR pandits across Noida sectors and Greater Noida.", blurbHi: "नोएडा सेक्टरों एवं ग्रेटर नोएडा में दिल्ली NCR के पंडित।" },
  { slug: "chandigarh", name: "Chandigarh", nameHi: "चंडीगढ़", state: "Chandigarh", stateHi: "चंडीगढ़", region: "north", languages: ["hi"], priceMultiplier: 1.15, panditCount: 55, landmark: "ISKCON Chandigarh", landmarkHi: "इस्कॉन चंडीगढ़", blurb: "Tricity pandits across Chandigarh, Mohali and Panchkula.", blurbHi: "चंडीगढ़, मोहाली एवं पंचकूला त्रि-शहर में पंडित।" },
  { slug: "bhubaneswar", name: "Bhubaneswar", nameHi: "भुवनेश्वर", state: "Odisha", stateHi: "ओडिशा", region: "east", languages: ["bn", "hi", "sa"], priceMultiplier: 1.0, panditCount: 60, landmark: "Lingaraj Mandir", landmarkHi: "लिंगराज मंदिर", blurb: "Odia Brahman pandits with Lingaraj-temple parampara.", blurbHi: "लिंगराज मंदिर परंपरा वाले ओडिया ब्राह्मण पंडित।" },
  { slug: "ranchi", name: "Ranchi", nameHi: "रांची", state: "Jharkhand", stateHi: "झारखंड", region: "east", languages: ["hi", "sa"], priceMultiplier: 0.95, panditCount: 45, landmark: "Pahari Mandir", landmarkHi: "पहाड़ी मंदिर", blurb: "Jharkhand pandits across Ranchi and Hatia.", blurbHi: "रांची एवं हटिया में झारखंड के पंडित।" },
  { slug: "raipur", name: "Raipur", nameHi: "रायपुर", state: "Chhattisgarh", stateHi: "छत्तीसगढ़", region: "central", languages: ["hi", "sa"], priceMultiplier: 0.9, panditCount: 40, landmark: "Mahamaya Mandir", landmarkHi: "महामाया मंदिर", blurb: "Chhattisgarh pandits across Raipur, Bhilai and Durg.", blurbHi: "रायपुर, भिलाई एवं दुर्ग में छत्तीसगढ़ के पंडित।" },
  { slug: "guwahati", name: "Guwahati", nameHi: "गुवाहाटी", state: "Assam", stateHi: "असम", region: "northeast", languages: ["bn", "hi", "sa"], priceMultiplier: 1.0, panditCount: 35, landmark: "Kamakhya Devi", landmarkHi: "कामाख्या देवी", blurb: "Kamakhya parampara Bardeori pandits across Guwahati.", blurbHi: "गुवाहाटी भर में कामाख्या परंपरा के बारदेवरी पंडित।" },
  { slug: "meerut", name: "Meerut", nameHi: "मेरठ", state: "Uttar Pradesh", stateHi: "उत्तर प्रदेश", region: "north", languages: ["hi", "sa"], priceMultiplier: 1.0, panditCount: 50, landmark: "Augarnath Mandir", landmarkHi: "औघड़नाथ मंदिर", blurb: "NCR-adjacent pandits across Meerut and surrounding districts.", blurbHi: "मेरठ एवं समीपवर्ती जिलों में NCR-निकटस्थ पंडित।" },
  { slug: "dehradun", name: "Dehradun", nameHi: "देहरादून", state: "Uttarakhand", stateHi: "उत्तराखंड", region: "north", languages: ["hi", "sa"], priceMultiplier: 1.05, panditCount: 50, landmark: "Tapkeshwar Mandir", landmarkHi: "टपकेश्वर मंदिर", blurb: "Garhwali and Kumaoni pandits across Dehradun valley.", blurbHi: "देहरादून घाटी में गढ़वाली एवं कुमाऊंनी पंडित।" },
];

export const CITY_BY_SLUG: Record<string, CityInfo> = Object.fromEntries(
  CITIES.map((c) => [c.slug, c]),
);

export function getCity(slug: string): CityInfo | undefined {
  return CITY_BY_SLUG[slug?.toLowerCase()];
}
