export interface PujaTypeInfo {
  /** URL-safe slug used in /puja/:type/:city */
  slug: string;
  name: string;
  nameHi: string;
  /** One-line "what is it for" intent */
  intent: string;
  intentHi: string;
  /** Approximate ritual duration */
  duration: string;
  durationHi: string;
  /** Base indicative price in INR before city multiplier */
  basePrice: number;
  /** When it is traditionally performed */
  bestTime: string;
  bestTimeHi: string;
  /** Up to 4 included items shown on landing */
  inclusions: string[];
  inclusionsHi: string[];
  /** Slug in PUJA_LANDINGS (if a long-form landing exists) for cross-link */
  landingSlug?: string;
}

export const PUJA_TYPES: PujaTypeInfo[] = [
  // ---- Existing long-form landings ----
  {
    slug: "satyanarayan-katha",
    name: "Satyanarayan Katha",
    nameHi: "सत्यनारायण कथा",
    intent: "Family prosperity, removal of obstacles, fulfilment of vows",
    intentHi: "पारिवारिक समृद्धि, बाधाओं का निवारण, मनोकामना पूर्ति",
    duration: "2–2.5 hours",
    durationHi: "2–2.5 घंटे",
    basePrice: 4100,
    bestTime: "Purnima or Thursday in Shukla Paksha",
    bestTimeHi: "पूर्णिमा अथवा शुक्ल पक्ष का गुरुवार",
    inclusions: ["Verified Vedic pandit", "Complete samagri kit", "Printed katha book", "HD recording"],
    inclusionsHi: ["सत्यापित वैदिक पंडित", "सम्पूर्ण पूजा सामग्री", "मुद्रित कथा पुस्तिका", "HD रिकॉर्डिंग"],
    landingSlug: "satyanarayan-katha",
  },
  {
    slug: "rudrabhishek",
    name: "Rudrabhishek",
    nameHi: "रुद्राभिषेक",
    intent: "Health, longevity, removal of grah dosha, Shiva blessings",
    intentHi: "स्वास्थ्य, दीर्घायु, ग्रह दोष निवारण एवं शिव कृपा",
    duration: "1.5–2 hours",
    durationHi: "1.5–2 घंटे",
    basePrice: 3500,
    bestTime: "Monday, Pradosh, or Maha Shivratri",
    bestTimeHi: "सोमवार, प्रदोष अथवा महाशिवरात्रि",
    inclusions: ["Verified Shaiva pandit", "Panchamrit & Bilva patra", "Shiva Sahasranamavali", "HD recording"],
    inclusionsHi: ["सत्यापित शैव पंडित", "पंचामृत एवं बिल्व पत्र", "शिव सहस्रनामावली", "HD रिकॉर्डिंग"],
    landingSlug: "rudrabhishek",
  },
  {
    slug: "griha-pravesh",
    name: "Griha Pravesh",
    nameHi: "गृह प्रवेश",
    intent: "Auspicious entry into a new home, Vastu shanti, family well-being",
    intentHi: "नए घर में शुभ प्रवेश, वास्तु शांति एवं परिवार का कल्याण",
    duration: "3–4 hours",
    durationHi: "3–4 घंटे",
    basePrice: 7500,
    bestTime: "Muhurat-aligned date in Magh, Phalgun, Vaishakh, Jyeshtha",
    bestTimeHi: "माघ, फाल्गुन, वैशाख अथवा ज्येष्ठ मास का शुभ मुहूर्त",
    inclusions: ["Vastu Shanti Hawan", "Navagraha Shanti", "Complete samagri kit", "HD recording + photos"],
    inclusionsHi: ["वास्तु शांति हवन", "नवग्रह शांति", "सम्पूर्ण पूजा सामग्री", "HD रिकॉर्डिंग एवं तस्वीरें"],
    landingSlug: "griha-pravesh",
  },
  {
    slug: "mahamrityunjaya-jaap",
    name: "Mahamrityunjaya Jaap",
    nameHi: "महामृत्युंजय जाप",
    intent: "Health, recovery from illness, removal of fear of untimely events",
    intentHi: "स्वास्थ्य लाभ, रोग निवृत्ति एवं अकाल मृत्यु के भय का नाश",
    duration: "Half-day (1.25 lakh jaap) or full-day",
    durationHi: "अर्ध-दिवस (सवा लाख जाप) अथवा पूर्ण दिवस",
    basePrice: 11000,
    bestTime: "Monday, Pradosh, Shravan",
    bestTimeHi: "सोमवार, प्रदोष, श्रावण मास",
    inclusions: ["1.25 lakh Mahamrityunjaya jaap", "Hawan", "Panditji's prayog mala", "HD recording"],
    inclusionsHi: ["सवा लाख महामृत्युंजय जाप", "हवन", "पंडित जी की प्रयोग माला", "HD रिकॉर्डिंग"],
    landingSlug: "mahamrityunjaya-jaap",
  },
  {
    slug: "navagraha-shanti",
    name: "Navagraha Shanti",
    nameHi: "नवग्रह शांति",
    intent: "Pacification of all nine planetary doshas indicated by kundli",
    intentHi: "कुंडली में दर्शाए सभी नौ ग्रहों के दोषों की शांति",
    duration: "3–4 hours",
    durationHi: "3–4 घंटे",
    basePrice: 6500,
    bestTime: "Within 40 days of dosha indication or as muhurat permits",
    bestTimeHi: "दोष ज्ञात होने के 40 दिनों के भीतर अथवा शुभ मुहूर्त अनुसार",
    inclusions: ["Nine-graha hawan", "Personalised sankalp", "Daan items for each graha", "HD recording"],
    inclusionsHi: ["नवग्रह हवन", "व्यक्तिगत संकल्प", "प्रत्येक ग्रह हेतु दान सामग्री", "HD रिकॉर्डिंग"],
    landingSlug: "navagraha-shanti",
  },

  // ---- New types ----
  {
    slug: "ganesh-puja",
    name: "Ganesh Puja",
    nameHi: "गणेश पूजा",
    intent: "Removal of obstacles before any new beginning",
    intentHi: "किसी भी नए कार्य के आरम्भ से पूर्व विघ्न निवारण",
    duration: "1–1.5 hours",
    durationHi: "1–1.5 घंटे",
    basePrice: 2500,
    bestTime: "Wednesday, Chaturthi, or Ganesh Chaturthi",
    bestTimeHi: "बुधवार, चतुर्थी अथवा गणेश चतुर्थी",
    inclusions: ["Vedic pandit", "Modak prasad", "Durva & red flowers", "Recording"],
    inclusionsHi: ["वैदिक पंडित", "मोदक प्रसाद", "दूर्वा एवं लाल पुष्प", "रिकॉर्डिंग"],
  },
  {
    slug: "lakshmi-puja",
    name: "Lakshmi Puja",
    nameHi: "लक्ष्मी पूजा",
    intent: "Wealth, business prosperity, financial stability",
    intentHi: "धन, व्यापार में समृद्धि एवं आर्थिक स्थिरता",
    duration: "1.5–2 hours",
    durationHi: "1.5–2 घंटे",
    basePrice: 3100,
    bestTime: "Friday, Diwali, or Akshaya Tritiya",
    bestTimeHi: "शुक्रवार, दीपावली अथवा अक्षय तृतीया",
    inclusions: ["Vedic pandit", "Shree Yantra puja", "Kuber sankalp", "Recording"],
    inclusionsHi: ["वैदिक पंडित", "श्री यंत्र पूजन", "कुबेर संकल्प", "रिकॉर्डिंग"],
  },
  {
    slug: "durga-puja",
    name: "Durga Puja",
    nameHi: "दुर्गा पूजा",
    intent: "Protection from negativity, courage, victory in disputes",
    intentHi: "नकारात्मकता से रक्षा, साहस एवं विवादों में विजय",
    duration: "2–3 hours",
    durationHi: "2–3 घंटे",
    basePrice: 4500,
    bestTime: "Navratri, Ashtami, Tuesday",
    bestTimeHi: "नवरात्रि, अष्टमी, मंगलवार",
    inclusions: ["Shakta-tradition pandit", "Durga Saptashati path", "Kanya pujan option", "Recording"],
    inclusionsHi: ["शाक्त परंपरा के पंडित", "दुर्गा सप्तशती पाठ", "कन्या पूजन का विकल्प", "रिकॉर्डिंग"],
  },
  {
    slug: "saraswati-puja",
    name: "Saraswati Puja",
    nameHi: "सरस्वती पूजा",
    intent: "Knowledge, academic success, blessings for students and artists",
    intentHi: "विद्या, शैक्षणिक सफलता एवं विद्यार्थियों व कलाकारों हेतु आशीर्वाद",
    duration: "1–1.5 hours",
    durationHi: "1–1.5 घंटे",
    basePrice: 2500,
    bestTime: "Vasant Panchami, Thursday",
    bestTimeHi: "वसंत पंचमी, गुरुवार",
    inclusions: ["Vedic pandit", "Vidya-arambh sankalp", "Saraswati stotra", "Recording"],
    inclusionsHi: ["वैदिक पंडित", "विद्यारम्भ संकल्प", "सरस्वती स्तोत्र", "रिकॉर्डिंग"],
  },
  {
    slug: "hanuman-puja",
    name: "Hanuman Puja",
    nameHi: "हनुमान पूजा",
    intent: "Strength, courage, removal of Shani-dosha and bhay",
    intentHi: "बल, साहस तथा शनि दोष व भय का निवारण",
    duration: "1.5 hours",
    durationHi: "1.5 घंटे",
    basePrice: 2800,
    bestTime: "Tuesday, Saturday, Hanuman Jayanti",
    bestTimeHi: "मंगलवार, शनिवार, हनुमान जयंती",
    inclusions: ["Sundarkand path", "Hanuman Chalisa 11 paath", "Sindoor abhishek", "Recording"],
    inclusionsHi: ["सुंदरकांड पाठ", "हनुमान चालीसा का 11 बार पाठ", "सिंदूर अभिषेक", "रिकॉर्डिंग"],
  },
  {
    slug: "kaal-sarp-dosh-nivaran",
    name: "Kaal Sarp Dosh Nivaran",
    nameHi: "कालसर्प दोष निवारण",
    intent: "Pacification of Kaal Sarp dosha indicated by Rahu-Ketu axis in kundli",
    intentHi: "कुंडली में राहु-केतु अक्ष से बने कालसर्प दोष की शांति",
    duration: "4–5 hours",
    durationHi: "4–5 घंटे",
    basePrice: 11000,
    bestTime: "Nag Panchami or Trimbakeshwar / Ujjain muhurat",
    bestTimeHi: "नाग पंचमी अथवा त्र्यंबकेश्वर / उज्जैन का शुभ मुहूर्त",
    inclusions: ["Kaal Sarp prayog", "Naag-Naagin idol visarjan", "Personalised sankalp", "Recording"],
    inclusionsHi: ["कालसर्प प्रयोग", "नाग-नागिन प्रतिमा विसर्जन", "व्यक्तिगत संकल्प", "रिकॉर्डिंग"],
  },
  {
    slug: "mangal-dosh-nivaran",
    name: "Mangal Dosh Nivaran",
    nameHi: "मंगल दोष निवारण",
    intent: "Pacification of Mangal (Mars) dosha — typical pre-marriage remedy",
    intentHi: "मंगल दोष की शांति — विवाह पूर्व का प्रमुख उपाय",
    duration: "3 hours",
    durationHi: "3 घंटे",
    basePrice: 7500,
    bestTime: "Tuesday, Mars hora",
    bestTimeHi: "मंगलवार, मंगल होरा",
    inclusions: ["Mangal hawan", "Hanuman Chalisa 21 paath", "Daan items", "Recording"],
    inclusionsHi: ["मंगल हवन", "हनुमान चालीसा का 21 बार पाठ", "दान सामग्री", "रिकॉर्डिंग"],
  },
  {
    slug: "pitra-dosh-nivaran",
    name: "Pitra Dosh Nivaran",
    nameHi: "पितृ दोष निवारण",
    intent: "Pacification of ancestor-related kundli doshas, family-line blessings",
    intentHi: "पितरों से सम्बंधित कुंडली दोषों की शांति एवं वंश पर आशीर्वाद",
    duration: "Half-day",
    durationHi: "अर्ध-दिवस",
    basePrice: 8500,
    bestTime: "Pitru Paksha, Amavasya",
    bestTimeHi: "पितृ पक्ष, अमावस्या",
    inclusions: ["Tarpan & Pind Daan sankalp", "Tripindi shraddh", "Brahman bhojan dakshina", "Recording"],
    inclusionsHi: ["तर्पण एवं पिंड दान संकल्प", "त्रिपिंडी श्राद्ध", "ब्राह्मण भोजन दक्षिणा", "रिकॉर्डिंग"],
  },
  {
    slug: "shani-shanti",
    name: "Shani Shanti",
    nameHi: "शनि शांति",
    intent: "Pacification of Shani sade-sati or dhaiya, professional stability",
    intentHi: "शनि साढ़े साती अथवा ढैय्या की शांति एवं कार्य में स्थिरता",
    duration: "2.5 hours",
    durationHi: "2.5 घंटे",
    basePrice: 5100,
    bestTime: "Saturday, Amavasya, Shani Jayanti",
    bestTimeHi: "शनिवार, अमावस्या, शनि जयंती",
    inclusions: ["Shani hawan", "Til oil abhishek", "Daan of black items", "Recording"],
    inclusionsHi: ["शनि हवन", "तेल अभिषेक", "काली वस्तुओं का दान", "रिकॉर्डिंग"],
  },
  {
    slug: "vastu-shanti",
    name: "Vastu Shanti",
    nameHi: "वास्तु शांति",
    intent: "Pacification of Vastu doshas in home, office or new construction",
    intentHi: "घर, कार्यालय अथवा नवनिर्माण में वास्तु दोषों की शांति",
    duration: "3 hours",
    durationHi: "3 घंटे",
    basePrice: 6100,
    bestTime: "Muhurat-aligned within 40 days of moving in or renovation",
    bestTimeHi: "गृह प्रवेश या नवीनीकरण के 40 दिनों के भीतर शुभ मुहूर्त",
    inclusions: ["Vastu purush sankalp", "Hawan at all four corners", "Vastu yantra sthapana", "Recording"],
    inclusionsHi: ["वास्तु पुरुष संकल्प", "चारों कोणों पर हवन", "वास्तु यंत्र स्थापना", "रिकॉर्डिंग"],
  },
  {
    slug: "gauri-ganesh-puja",
    name: "Gauri Ganesh Puja",
    nameHi: "गौरी गणेश पूजा",
    intent: "Mandatory pre-puja invocation before any Vedic ceremony or wedding",
    intentHi: "किसी भी वैदिक अनुष्ठान या विवाह पूर्व अनिवार्य आह्वान पूजा",
    duration: "1 hour",
    durationHi: "1 घंटा",
    basePrice: 2100,
    bestTime: "Before any major puja or wedding rite",
    bestTimeHi: "किसी भी प्रमुख पूजा अथवा विवाह संस्कार से पूर्व",
    inclusions: ["Gauri & Ganesh sthapana", "Sankalp", "Modak prasad", "Recording"],
    inclusionsHi: ["गौरी एवं गणेश स्थापना", "संकल्प", "मोदक प्रसाद", "रिकॉर्डिंग"],
  },
  {
    slug: "bhoomi-pujan",
    name: "Bhoomi Pujan",
    nameHi: "भूमि पूजन",
    intent: "Sanctification of land before construction begins",
    intentHi: "निर्माण कार्य आरम्भ करने से पूर्व भूमि का पूजन",
    duration: "2 hours",
    durationHi: "2 घंटे",
    basePrice: 4500,
    bestTime: "Muhurat aligned with construction start date",
    bestTimeHi: "निर्माण आरम्भ की तिथि के अनुसार शुभ मुहूर्त",
    inclusions: ["Bhoomi sankalp", "Naag-bali offering", "Foundation stone puja", "Recording"],
    inclusionsHi: ["भूमि संकल्प", "नाग-बलि अर्पण", "शिलान्यास पूजन", "रिकॉर्डिंग"],
  },
  {
    slug: "namkaran-sanskar",
    name: "Namkaran Sanskar",
    nameHi: "नामकरण संस्कार",
    intent: "Vedic naming ceremony for newborn (10th–12th day)",
    intentHi: "नवजात शिशु का वैदिक नामकरण संस्कार (10वें–12वें दिन)",
    duration: "1.5 hours",
    durationHi: "1.5 घंटे",
    basePrice: 3500,
    bestTime: "10th, 11th or 12th day after birth",
    bestTimeHi: "जन्म के 10वें, 11वें अथवा 12वें दिन",
    inclusions: ["Vedic pandit", "Janma-nakshatra calculation", "Akshat in baby's ear", "Recording"],
    inclusionsHi: ["वैदिक पंडित", "जन्म नक्षत्र गणना", "शिशु के कान में अक्षत", "रिकॉर्डिंग"],
  },
  {
    slug: "mundan-sanskar",
    name: "Mundan Sanskar",
    nameHi: "मुंडन संस्कार",
    intent: "First hair-cutting ceremony for child (chaul karma)",
    intentHi: "शिशु का प्रथम मुंडन संस्कार (चौल कर्म)",
    duration: "1.5–2 hours",
    durationHi: "1.5–2 घंटे",
    basePrice: 3800,
    bestTime: "Odd year of child's age — 1, 3, 5, 7",
    bestTimeHi: "बच्चे की विषम आयु में — 1, 3, 5, 7 वर्ष",
    inclusions: ["Vedic pandit", "Hawan & sankalp", "Coordination with naai", "Recording"],
    inclusionsHi: ["वैदिक पंडित", "हवन एवं संकल्प", "नाई के साथ समन्वय", "रिकॉर्डिंग"],
  },
  {
    slug: "annaprashan",
    name: "Annaprashan Sanskar",
    nameHi: "अन्नप्राशन संस्कार",
    intent: "Baby's first solid food ceremony (6th–8th month)",
    intentHi: "शिशु का प्रथम अन्नप्राशन संस्कार (6ठे–8वें माह में)",
    duration: "1 hour",
    durationHi: "1 घंटा",
    basePrice: 2800,
    bestTime: "6th–8th month, muhurat-aligned day",
    bestTimeHi: "6ठे–8वें माह में शुभ मुहूर्त वाला दिन",
    inclusions: ["Vedic pandit", "Sankalp", "First-food kheer offering", "Recording"],
    inclusionsHi: ["वैदिक पंडित", "संकल्प", "प्रथम अन्न रूप में खीर अर्पण", "रिकॉर्डिंग"],
  },
];

export const PUJA_TYPE_BY_SLUG: Record<string, PujaTypeInfo> = Object.fromEntries(
  PUJA_TYPES.map((p) => [p.slug, p]),
);

export function getPujaType(slug: string): PujaTypeInfo | undefined {
  return PUJA_TYPE_BY_SLUG[slug?.toLowerCase()];
}
