import { useMemo } from "react";
import { Link, useParams } from "wouter";
import { useQuery } from "@tanstack/react-query";
import { BadgeCheck, SearchX, ShieldAlert } from "lucide-react";
import PageSeo from "@/components/PageSeo";
import { PanditMembershipCard, type PublicPanditCredential } from "@/components/pandit/PanditMembershipCard";
import { Button } from "@/components/ui/button";

type VerifyResponse = PublicPanditCredential & { lifetimeMembership?: boolean; registrationAssignedAt?: string | null };
export default function VerifyPanditPage() {
  const { registrationNo = "" } = useParams<{ registrationNo: string }>(); const valid = /^\d{10}$/.test(registrationNo);
  const result = useQuery<VerifyResponse>({ queryKey: ["/api/pandits/verify", registrationNo], enabled: valid, retry: false, queryFn: async () => { const response = await fetch(`/api/pandits/verify/${encodeURIComponent(registrationNo)}`); if (!response.ok) throw new Error("not-found"); return response.json(); } });
  const schema = useMemo(() => result.data?.status === "verified" ? [{ id: "pandit-verification-credential", payload: { "@context": "https://schema.org", "@type": "Person", name: result.data.name, image: result.data.image || undefined, jobTitle: "Vedic Pandit", identifier: result.data.registrationNo, url: result.data.profilePath ? new URL(result.data.profilePath, window.location.origin).toString() : undefined, hasCredential: { "@type": "EducationalOccupationalCredential", "@id": `${new URL(`/verify-pandit/${result.data.registrationNo}`, window.location.origin).toString()}#credential`, credentialCategory: "Lifetime Membership", recognizedBy: { "@type": "Organization", "@id": `${window.location.origin}/#organization` } } } }] : [], [result.data]);
  if (!valid || result.isError) return <div className="grid min-h-[100dvh] place-items-center bg-[#f6eddb] px-5 text-center"><PageSeo title="Pandit verification unavailable | Vedic Tatva" description="This Vedic Tatva Pandit credential could not be verified." canonical={`/verify-pandit/${registrationNo}`} noindex/><div className="max-w-md border border-[#d6b66e] bg-[#fff8e9] p-9 shadow-[0_16px_45px_rgba(77,22,25,.12)]"><SearchX className="mx-auto h-11 w-11 text-[#7a2630]"/><h1 className="mt-5 font-serif text-3xl text-[#551720]">Credential not found</h1><p className="mt-3 text-sm leading-6 text-[#70574c]">Please check the 10-digit registration number and try again. We do not publish unverified records.</p><Link href="/book-pandit-online" className="mt-6 inline-flex"><Button className="bg-[#6d2b35] text-[#fff4d9]">Browse verified Pandits</Button></Link></div></div>;
  if (result.isLoading) return <div className="min-h-[100dvh] bg-[#f6eddb] p-6"><div className="mx-auto mt-20 h-96 max-w-3xl animate-pulse rounded-3xl bg-[#e5d2ab]"/></div>;
  const credential = result.data!;
  if (credential.status === "inactive") return <div className="grid min-h-[100dvh] place-items-center bg-[#f6eddb] px-5 text-center"><PageSeo title={`Membership status | Vedic Tatva`} description="Vedic Tatva Pandit membership status." canonical={`/verify-pandit/${credential.registrationNo}`} noindex/><div className="max-w-md border border-[#d6b66e] bg-[#fff8e9] p-9 shadow-[0_16px_45px_rgba(77,22,25,.12)]"><ShieldAlert className="mx-auto h-11 w-11 text-[#7a2630]"/><h1 className="mt-5 font-serif text-3xl text-[#551720]">Membership not active</h1><p className="mt-3 text-sm leading-6 text-[#70574c]">Registration no. <span className="font-mono font-semibold">{credential.registrationNo}</span> is not currently active. No profile details are available.</p></div></div>;
  return <main className="min-h-[100dvh] bg-[#f6eddb] px-4 py-10 sm:py-16"><PageSeo title={`${credential.name} — Vedic Tatva Pandit verification`} description={`Verify the lifetime Vedic Tatva membership credential for ${credential.name}.`} canonical={`/verify-pandit/${credential.registrationNo}`} ogType="profile" ogImage={credential.image || undefined} schemas={schema}/><div className="mx-auto max-w-4xl"><div className="mb-8 text-center"><div className="inline-flex items-center gap-2 border-b border-[#c79d49] pb-2 text-[10px] font-bold uppercase tracking-[.28em] text-[#865d19]"><BadgeCheck className="h-4 w-4"/>Official credential verification</div><h1 className="mt-4 font-serif text-4xl text-[#551720]">Verified with Vedic Tatva</h1><p className="mt-3 text-sm text-[#70574c]">This public credential confirms a current, approved lifetime membership.</p></div><PanditMembershipCard credential={credential}/>{credential.profilePath && <div className="mt-7 text-center"><Link href={credential.profilePath} className="inline-flex"><Button variant="outline" className="border-[#7b2930] text-[#69232b]">View public Pandit profile</Button></Link></div>}</div></main>;
}