import { useEffect, useMemo, useState } from "react";
import { ChevronLeft, ChevronRight, CalendarDays } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { panditApi } from "@/lib/panditAuth";
import { useToast } from "@/hooks/use-toast";
import { Booking, BookingDetailDialog } from "@/components/pandit/PanditBookingWorkflow";
export default function PanditCalendar({ refresh }: { refresh: () => void }) {
  const { toast } = useToast(); const [month, setMonth] = useState(new Date().toISOString().slice(0, 7)); const [items, setItems] = useState<Booking[]>([]); const [open, setOpen] = useState<Booking | null>(null); const [loading, setLoading] = useState(true);
  useEffect(() => { setLoading(true); panditApi("GET", `/api/pandit/bookings/calendar?month=${month}`).then(r => setItems(r.bookings || [])).catch((e: any) => toast({ title: "Calendar unavailable", description: e.message, variant: "destructive" })).finally(() => setLoading(false)); }, [month]);
  const date = new Date(`${month}-01T00:00:00`); const days = new Date(date.getFullYear(), date.getMonth() + 1, 0).getDate(); const start = date.getDay(); const map = useMemo(() => items.reduce((a, b) => { (a[b.date] ||= []).push(b); return a; }, {} as Record<string, Booking[]>), [items]);
  const move = (amount: number) => { const next = new Date(date); next.setMonth(next.getMonth() + amount); setMonth(next.toISOString().slice(0, 7)); };
  return <div className="space-y-4"><div><p className="text-[11px] font-bold uppercase tracking-[.2em] text-[#946c16]">Your calendar</p><h2 className="mt-1 font-serif text-3xl text-[#55252d]">Calendar</h2></div><Card className="border-[#d8c8ae] bg-[#fffdf8]"><CardContent className="p-4"><div className="mb-4 flex items-center justify-between"><Button size="icon" variant="outline" onClick={() => move(-1)} aria-label="Previous month"><ChevronLeft className="h-4 w-4" /></Button><h3 className="font-serif text-xl text-[#55252d]">{date.toLocaleDateString(undefined, { month: "long", year: "numeric" })}</h3><Button size="icon" variant="outline" onClick={() => move(1)} aria-label="Next month"><ChevronRight className="h-4 w-4" /></Button></div>{loading ? <div className="grid grid-cols-7 gap-1 animate-pulse">{Array.from({ length: 35 }, (_, i) => <div key={i} className="aspect-square rounded bg-[#efe4cf]" />)}</div> : <><div className="mb-1 grid grid-cols-7 text-center text-[10px] font-bold uppercase text-[#806f5e]">{["S","M","T","W","T","F","S"].map((d, i) => <span key={i}>{d}</span>)}</div><div className="grid grid-cols-7 gap-1">{Array.from({ length: start }, (_, i) => <div key={`pad-${i}`} />)}{Array.from({ length: days }, (_, i) => { const day = i + 1; const key = `${month}-${String(day).padStart(2, "0")}`; const dayItems = map[key] || []; return <button key={day} onClick={() => dayItems[0] && setOpen(dayItems[0])} className={`min-h-14 rounded border p-1 text-left text-xs ${dayItems.length ? "border-[#e6b957] bg-[#f2e6d2]" : "border-[#e4d7c3]"}`} data-testid={`cal-day-${day}`}><b>{day}</b>{dayItems.slice(0, 2).map(b => <span key={b.id} className={`mt-1 block truncate rounded px-1 text-[9px] ${b.status === "accepted" ? "bg-emerald-100 text-emerald-800" : "bg-amber-100 text-amber-800"}`}>{b.timeSlot}</span>)}</button>; })}</div></>} </CardContent></Card><BookingDetailDialog booking={open} onClose={() => setOpen(null)} onUpdated={() => { setOpen(null); refresh(); }} /></div>;
}