import { db } from "./db";
import { seoPages, type InsertSeoPage } from "@shared/schema";
import { sql } from "drizzle-orm";

const SEED: InsertSeoPage[] = [
  {
    pagePath: "/",
    metaTitle: "Vedic Tatva — Sacred Living, Authentic Puja, Pandits & Pilgrimages",
    metaDescription: "Book verified pandits, perform puja online, shop authentic puja essentials, and plan sacred pilgrimages. Vedic wisdom for modern devotees, delivered worldwide.",
    canonicalUrl: "/",
    ogType: "website",
    priority: 1.0,
    changeFreq: "daily",
  },
  {
    pagePath: "/shop",
    metaTitle: "Spiritual Shop — Rudraksha, Idols, Puja & Havan Samagri | Vedic Tatva",
    metaDescription: "Shop lab-certified Rudraksha, hand-crafted idols, sacred samagri, malas and energised wearables. Blessed and shipped from Bharat with COD and free shipping over ₹499.",
    metaKeywords: "rudraksha online, puja samagri, hindu deity idols, havan samagri, mala beads, vedic store india, spiritual products",
    canonicalUrl: "/shop",
    priority: 0.9,
    changeFreq: "daily",
  },
  {
    pagePath: "/blog",
    metaTitle: "Vedic Wisdom Blog — Rituals, Festivals & Spiritual Living | Vedic Tatva",
    metaDescription: "Authentic guides on Hindu rituals, festivals, mantras, jyotish and sacred living — written by pandits and scholars at Vedic Tatva.",
    canonicalUrl: "/blog",
    priority: 0.8,
    changeFreq: "weekly",
  },
  {
    pagePath: "/pind-daan",
    metaTitle: "Online Pind Daan, Tarpan & Shradh — Gaya, Kashi, Haridwar | Vedic Tatva",
    metaDescription: "Book authentic Pind Daan, Tarpan and Shradh online at Gaya, Kashi, Haridwar or as a yearly remote service from anywhere. Verified Tirth Purohits, live video Sankalp, full proof and worldwide prasad delivery.",
    canonicalUrl: "/pind-daan",
    priority: 0.9,
    changeFreq: "weekly",
  },
  {
    pagePath: "/pind-daan-gaya",
    metaTitle: "Online Pind Daan in Gaya — Moksha at Vishnupad & Phalgu | Vedic Tatva",
    metaDescription: "Authentic Gaya Pind Daan with verified Karmakandi pandits at Vishnupad and Phalgu. Live video sankalp, ritual proof, prasad delivery worldwide.",
    canonicalUrl: "/pind-daan-gaya",
    priority: 0.85,
    changeFreq: "weekly",
  },
  {
    pagePath: "/pind-daan-kashi",
    metaTitle: "Online Pind Daan in Kashi — Liberation at Manikarnika | Vedic Tatva",
    metaDescription: "Book Kashi Pind Daan and Shradh at Manikarnika and Pishachmochan with verified Tirth Purohits. Live sankalp, full proof, worldwide prasad delivery.",
    canonicalUrl: "/pind-daan-kashi",
    priority: 0.85,
    changeFreq: "weekly",
  },
  {
    pagePath: "/pind-daan-haridwar",
    metaTitle: "Online Pind Daan in Haridwar — Shradh at Har Ki Pauri | Vedic Tatva",
    metaDescription: "Haridwar Pind Daan and Pitru Dosh nivaran at Har Ki Pauri and Narayani Shila. Verified pandits, live video sankalp, prasad delivery worldwide.",
    canonicalUrl: "/pind-daan-haridwar",
    priority: 0.85,
    changeFreq: "weekly",
  },
  {
    pagePath: "/temple-tourism",
    metaTitle: "Temple Tourism India — Curated Spiritual Journeys | Vedic Tatva",
    metaDescription: "Curated temple tours and spiritual journeys across India. Discover ancient temples, experience authentic rituals, and travel with verified guides.",
    canonicalUrl: "/temple-tourism",
    priority: 0.7,
    changeFreq: "monthly",
  },
  {
    pagePath: "/tirth-yatra",
    metaTitle: "Tirth Yatra — Sacred Pilgrimages of Bharat | Vedic Tatva",
    metaDescription: "Plan and book sacred pilgrimages — Char Dham, Jyotirlingas, Shakti Peethas and more. Verified guides, comfortable stays and authentic darshan experiences.",
    canonicalUrl: "/tirth-yatra",
    priority: 0.85,
    changeFreq: "weekly",
  },
  {
    pagePath: "/ai-baby-names",
    metaTitle: "AI Baby Names — Vedic, Sanskrit & Nakshatra-Based | Vedic Tatva",
    metaDescription: "Generate meaningful Hindu baby names by nakshatra, rashi, deity and meaning using our free AI Vedic baby name generator.",
    canonicalUrl: "/ai-baby-names",
    priority: 0.7,
    changeFreq: "monthly",
  },
  {
    pagePath: "/tools/tithi-calculator",
    metaTitle: "Hindu Tithi Calculator — Panchang & Auspicious Dates | Vedic Tatva",
    metaDescription: "Free Hindu Tithi calculator with Panchang, nakshatra, yoga and karana for any date. Find auspicious muhurat, festival dates and shradh tithis.",
    canonicalUrl: "/tools/tithi-calculator",
    priority: 0.75,
    changeFreq: "weekly",
  },
  {
    pagePath: "/spiritual-essentials",
    metaTitle: "Puja Essentials — Daily Puja & Sadhana Kits | Vedic Tatva",
    metaDescription: "Curated puja essentials for daily puja and sadhana — diyas, incense, asanas, japa malas and more. Authentic, energised and ready to ship.",
    canonicalUrl: "/spiritual-essentials",
    priority: 0.8,
    changeFreq: "weekly",
  },
  {
    pagePath: "/pandits",
    metaTitle: "Verified Vedic Pandits — Book Online for Puja & Havan | Vedic Tatva",
    metaDescription: "Browse and book verified Vedic pandits across India for authentic puja, havan, and samskara ceremonies — at your home or online.",
    canonicalUrl: "/pandits",
    priority: 0.85,
    changeFreq: "weekly",
  },
  {
    pagePath: "/puja",
    metaTitle: "Online Puja Booking — Verified Pandits, Live Sankalp | Vedic Tatva",
    metaDescription: "Book authentic online puja with verified pandits. Live video sankalp, prasad delivery and full ritual proof. Choose from popular pujas pan-India.",
    canonicalUrl: "/puja",
    priority: 0.9,
    changeFreq: "weekly",
  },
  {
    pagePath: "/astrology",
    metaTitle: "Vedic Astrology — Talk to Verified Jyotishis | Vedic Tatva",
    metaDescription: "Consult verified Vedic astrologers for kundli, marriage matching, career, and remedies. Chat or call online with authentic jyotishis.",
    canonicalUrl: "/astrology",
    priority: 0.85,
    changeFreq: "weekly",
  },
  {
    pagePath: "/ai-kundli",
    metaTitle: "AI Kundli — Free Vedic Birth Chart & Predictions | Vedic Tatva",
    metaDescription: "Generate your free AI-powered Vedic Kundli with detailed predictions, dasha, yogas, and remedies based on traditional jyotish principles.",
    canonicalUrl: "/ai-kundli",
    priority: 0.8,
    changeFreq: "monthly",
  },
  {
    pagePath: "/ai-palm-reading",
    metaTitle: "AI Palm Reading — Free Vedic Hastrekha Analysis | Vedic Tatva",
    metaDescription: "Upload your palm photo for an AI-powered Vedic palmistry reading. Get insights into life, career, love, and health lines instantly.",
    canonicalUrl: "/ai-palm-reading",
    priority: 0.7,
    changeFreq: "monthly",
  },
  {
    pagePath: "/premium-kundli-pdf",
    metaTitle: "Premium Vedic Kundli PDF — Detailed 80-Page Report | Vedic Tatva",
    metaDescription: "Order your premium 80-page Vedic Kundli PDF report with dashas, doshas, predictions, and personalised remedies. Crafted by certified jyotishis.",
    canonicalUrl: "/premium-kundli-pdf",
    priority: 0.75,
    changeFreq: "monthly",
  },
  {
    pagePath: "/zodiac-rashifal",
    metaTitle: "Daily Rashifal — Vedic Horoscope for All 12 Rashis | Vedic Tatva",
    metaDescription: "Read today's accurate Vedic Rashifal for all 12 zodiac signs — career, love, health and lucky number predictions, updated daily.",
    canonicalUrl: "/zodiac-rashifal",
    priority: 0.8,
    changeFreq: "daily",
  },
  {
    pagePath: "/panchang-calendar",
    metaTitle: "Hindu Panchang Calendar — Tithi, Nakshatra, Muhurat | Vedic Tatva",
    metaDescription: "Daily Hindu Panchang with tithi, nakshatra, yoga, karana, sunrise, sunset and shubh muhurat for any city in India.",
    canonicalUrl: "/panchang-calendar",
    priority: 0.8,
    changeFreq: "daily",
  },
  {
    pagePath: "/muhurat-finder",
    metaTitle: "Shubh Muhurat Finder — Auspicious Date & Time Tool | Vedic Tatva",
    metaDescription: "Find shubh muhurat for marriage, griha pravesh, vehicle purchase, and other ceremonies based on traditional Vedic astrology.",
    canonicalUrl: "/muhurat-finder",
    priority: 0.75,
    changeFreq: "weekly",
  },
  {
    pagePath: "/vastu-compass",
    metaTitle: "Vastu Compass — Free Online Direction Finder | Vedic Tatva",
    metaDescription: "Use our free Vastu compass to align your home, office, or puja room with Vedic Vastu Shastra principles for prosperity and harmony.",
    canonicalUrl: "/vastu-compass",
    priority: 0.7,
    changeFreq: "monthly",
  },
  {
    pagePath: "/scripture-search",
    metaTitle: "Scripture Search — Vedas, Upanishads, Gita & Puranas | Vedic Tatva",
    metaDescription: "Search and explore verses from the Vedas, Upanishads, Bhagavad Gita, Ramayana, Mahabharata and Puranas with translations and commentary.",
    canonicalUrl: "/scripture-search",
    priority: 0.75,
    changeFreq: "weekly",
  },
  {
    pagePath: "/kathas",
    metaTitle: "Hindu Kathas — Sacred Stories & Vrat Vidhi | Vedic Tatva",
    metaDescription: "Read authentic Satyanarayan, Vaibhav Lakshmi, Santoshi Mata and other Hindu kathas with vrat vidhi and aarti.",
    canonicalUrl: "/kathas",
    priority: 0.7,
    changeFreq: "monthly",
  },
  {
    pagePath: "/matrimony",
    metaTitle: "Vedic Matrimony — Kundli-Matched Profiles | Vedic Tatva",
    metaDescription: "Find your life partner with Vedic Tatva Matrimony — kundli-matched, verified profiles with traditional and modern values.",
    canonicalUrl: "/matrimony",
    priority: 0.8,
    changeFreq: "weekly",
  },
  {
    pagePath: "/donations",
    metaTitle: "Temple Donations — Support Sacred Causes | Vedic Tatva",
    metaDescription: "Donate to verified temples, gaushalas, and dharmic causes across India. Receive prasad and a digital certificate of your contribution.",
    canonicalUrl: "/donations",
    priority: 0.7,
    changeFreq: "monthly",
  },
  {
    pagePath: "/subscriptions",
    metaTitle: "Spiritual Subscriptions — Monthly Sadhana Boxes | Vedic Tatva",
    metaDescription: "Subscribe to monthly puja essentials, samagri kits, and curated sadhana boxes delivered across India.",
    canonicalUrl: "/subscriptions",
    priority: 0.7,
    changeFreq: "monthly",
  },
  {
    pagePath: "/membership",
    metaTitle: "Vedic Tatva Membership — Exclusive Spiritual Benefits",
    metaDescription: "Become a Vedic Tatva member for priority puja booking, exclusive discounts, free consultations, and curated spiritual content.",
    canonicalUrl: "/membership",
    priority: 0.7,
    changeFreq: "monthly",
  },
  {
    pagePath: "/refer",
    metaTitle: "Refer & Earn — Share Vedic Tatva With Loved Ones",
    metaDescription: "Refer friends and family to Vedic Tatva and earn rewards on every successful sign-up and purchase.",
    canonicalUrl: "/refer",
    priority: 0.6,
    changeFreq: "monthly",
  },
  {
    pagePath: "/lucky-draw",
    metaTitle: "Lucky Draw — Win Sacred Spiritual Gifts | Vedic Tatva",
    metaDescription: "Participate in our monthly lucky draw to win authentic spiritual gifts, energised Rudraksha, and free puja bookings.",
    canonicalUrl: "/lucky-draw",
    priority: 0.6,
    changeFreq: "weekly",
  },
  {
    pagePath: "/pilgrimage-card",
    metaTitle: "Pilgrimage Card — Discounts at 100+ Temples | Vedic Tatva",
    metaDescription: "Get exclusive priority darshan and accommodation discounts at 100+ partner temples across India with the Vedic Tatva Pilgrimage Card.",
    canonicalUrl: "/pilgrimage-card",
    priority: 0.7,
    changeFreq: "monthly",
  },
  {
    pagePath: "/virtual-puja",
    metaTitle: "Virtual Puja — Live Online Pujas From Sacred Temples | Vedic Tatva",
    metaDescription: "Join live virtual pujas streamed from sacred temples across India. Sankalp, prasad delivery and ritual proof included.",
    canonicalUrl: "/virtual-puja",
    priority: 0.8,
    changeFreq: "weekly",
  },
  {
    pagePath: "/about",
    metaTitle: "About Vedic Tatva — Our Spiritual Mission",
    metaDescription: "Learn about Vedic Tatva — our mission to make authentic Vedic wisdom and rituals accessible to devotees worldwide.",
    canonicalUrl: "/about",
    priority: 0.5,
    changeFreq: "yearly",
  },
  {
    pagePath: "/contact",
    metaTitle: "Contact Vedic Tatva — Customer Support & Help",
    metaDescription: "Get in touch with Vedic Tatva for puja bookings, product queries, or spiritual guidance. Email, WhatsApp and phone support available.",
    canonicalUrl: "/contact",
    priority: 0.5,
    changeFreq: "yearly",
  },
  {
    pagePath: "/careers",
    metaTitle: "Careers at Vedic Tatva — Join Our Spiritual Mission",
    metaDescription: "Explore career opportunities at Vedic Tatva. Join a passionate team building India's most trusted spiritual platform.",
    canonicalUrl: "/careers",
    priority: 0.4,
    changeFreq: "monthly",
  },
  {
    pagePath: "/franchise",
    metaTitle: "Vedic Tatva Franchise — Partner With Us",
    metaDescription: "Become a Vedic Tatva franchise partner and bring authentic spiritual services to your city.",
    canonicalUrl: "/franchise",
    priority: 0.5,
    changeFreq: "yearly",
  },
  {
    pagePath: "/become-pandit",
    metaTitle: "Become a Vedic Tatva Pandit — Apply Online",
    metaDescription: "Apply to join Vedic Tatva's verified pandit network. Authentic karmakandi pandits with traditional training are welcome.",
    canonicalUrl: "/become-pandit",
    priority: 0.6,
    changeFreq: "monthly",
  },
  {
    pagePath: "/become-astrologer",
    metaTitle: "Become a Vedic Tatva Astrologer — Apply Online",
    metaDescription: "Join the Vedic Tatva astrologer network. Certified jyotishis with proven expertise are invited to apply.",
    canonicalUrl: "/become-astrologer",
    priority: 0.6,
    changeFreq: "monthly",
  },
  {
    pagePath: "/refund-policy",
    metaTitle: "Refund Policy | Vedic Tatva",
    metaDescription: "Read Vedic Tatva's refund policy for products, puja bookings, and consultations.",
    canonicalUrl: "/refund-policy",
    priority: 0.3,
    changeFreq: "yearly",
  },
  {
    pagePath: "/terms-conditions",
    metaTitle: "Terms & Conditions | Vedic Tatva",
    metaDescription: "Terms and conditions governing the use of Vedic Tatva services and website.",
    canonicalUrl: "/terms-conditions",
    priority: 0.3,
    changeFreq: "yearly",
  },
  {
    pagePath: "/privacy-policy",
    metaTitle: "Privacy Policy | Vedic Tatva",
    metaDescription: "How Vedic Tatva collects, uses, and protects your personal information and data.",
    canonicalUrl: "/privacy-policy",
    priority: 0.3,
    changeFreq: "yearly",
  },
  {
    pagePath: "/shipping-policy",
    metaTitle: "Shipping Policy | Vedic Tatva",
    metaDescription: "Vedic Tatva shipping rates, delivery timelines, and international shipping information.",
    canonicalUrl: "/shipping-policy",
    priority: 0.3,
    changeFreq: "yearly",
  },
];

export async function seedSeoPages() {
  if (SEED.length === 0) return;
  try {
    await db
      .insert(seoPages)
      .values(SEED)
      .onConflictDoNothing({ target: seoPages.pagePath });
    console.log(`[seo-seed] Ensured ${SEED.length} SEO page rows`);
  } catch (err) {
    console.error("[seo-seed] failed:", err);
  }
}
