import { useEffect, useState } from "react";
import { ArrowDownLeft, ArrowUpRight, ExternalLink, GitBranch, Search, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import type { Edge, Entity, EntityType } from "./types";

export const label = (v: string) => v.replaceAll("_", " ").toLowerCase().replace(/\b\w/g, c => c.toUpperCase());
export function EntityTag({ entity }: { entity: Entity }) { return <span className="text-[10px] font-bold tracking-[.13em] text-primary/75">{entity.type}{entity.discriminator ? ` · ${entity.discriminator}` : ""}</span>; }
export function EntityList({ items, onPick, empty = "No records match this view." }: { items?: Entity[]; onPick: (e: Entity) => void; empty?: string }) {
  if (!items?.length) return <div className="rounded-xl border border-dashed border-border bg-muted/30 px-5 py-10 text-center text-sm text-muted-foreground">{empty}</div>;
  return <div className="divide-y divide-border rounded-xl border border-border bg-card overflow-hidden">{items.map(e => <button key={`${e.type}-${e.id}-${e.discriminator || ""}`} onClick={() => onPick(e)} className="w-full text-left px-4 py-3.5 hover:bg-accent/45 focus-visible:outline-none focus-visible:bg-accent/60 transition-colors"><div className="flex items-center justify-between gap-4"><div className="min-w-0"><EntityTag entity={e} /><div className="font-semibold truncate">{e.name}</div></div><div className="shrink-0 text-right text-xs text-muted-foreground">{e.connectionCount ?? 0} links</div></div></button>)}</div>;
}
export function SearchField({ value, onChange, placeholder = "Search names…" }: { value: string; onChange: (v: string) => void; placeholder?: string }) {
  const [local, setLocal] = useState(value); useEffect(() => { const t = setTimeout(() => onChange(local), 280); return () => clearTimeout(t); }, [local, onChange]); return <div className="relative"><Search className="absolute left-3 top-3.5 h-4 w-4 text-muted-foreground" /><Input value={local} onChange={e => setLocal(e.target.value)} className="pl-9 bg-card" placeholder={placeholder} /></div>;
}
export function EdgeGroups({ title, groups, direction, onRemove }: { title: string; groups: Record<string, Edge[]>; direction: "incoming" | "outgoing"; onRemove: (edge: Edge) => void }) {
  const Icon = direction === "incoming" ? ArrowDownLeft : ArrowUpRight;
  return <section className="rounded-xl border border-border bg-card overflow-hidden"><header className="flex items-center gap-2 px-4 py-3 border-b border-border"><Icon className="w-4 h-4 text-secondary-foreground" /><h3 className="font-serif font-semibold">{title}</h3></header>{Object.keys(groups).length === 0 ? <p className="p-5 text-sm text-muted-foreground">No {direction} relationships.</p> : <div className="divide-y divide-border">{Object.entries(groups).map(([rel, edges]) => <div key={rel} className="p-4"><p className="mb-2 text-[10px] tracking-[.15em] font-bold text-muted-foreground uppercase">{label(rel)}</p>{edges.map(edge => <div key={edge.id} className="flex items-center gap-2 py-2"><GitBranch className="w-3.5 h-3.5 text-secondary" /><div className="min-w-0 flex-1"><span className="text-sm font-medium">{edge.entity?.name || "Missing entity"}</span>{edge.stale && <Badge variant="destructive" className="ml-2 text-[9px]">Stale</Badge>}</div><Badge variant="outline" className="text-[9px]">{edge.status}</Badge><Button variant="ghost" size="icon" onClick={() => onRemove(edge)} aria-label="Remove relationship"><Trash2 className="w-3.5 h-3.5 text-destructive" /></Button></div>)}</div>)}</div>}</section>;
}
export function Confirm({ open, onOpenChange, title, description, onConfirm, pending }: { open: boolean; onOpenChange: (v: boolean) => void; title: string; description: string; onConfirm: () => void; pending?: boolean }) { return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>{title}</DialogTitle><DialogDescription>{description}</DialogDescription></DialogHeader><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button variant="destructive" onClick={onConfirm} disabled={pending}>{pending ? "Removing…" : "Remove"}</Button></DialogFooter></DialogContent></Dialog>; }
export function DetailMap({ entity, edges }: { entity: Entity; edges: Edge[] }) { const visible = edges.slice(0, 6); return <div className="rounded-xl border border-border bg-[linear-gradient(135deg,hsl(var(--accent)/.35),hsl(var(--card)))] p-4 overflow-hidden"><div className="flex justify-between mb-2"><span className="text-[10px] tracking-[.15em] font-bold uppercase text-muted-foreground">Relationship field</span><span className="text-xs text-muted-foreground">{edges.length} records</span></div><svg viewBox="0 0 640 200" className="w-full h-48" role="img" aria-label={`Relationship map for ${entity.name}`}><circle cx="320" cy="100" r="42" fill="hsl(var(--primary))" /><text x="320" y="96" textAnchor="middle" fill="hsl(var(--primary-foreground))" fontSize="13" fontWeight="700">{entity.name.slice(0, 18)}</text><text x="320" y="114" textAnchor="middle" fill="hsl(var(--primary-foreground))" fontSize="9">{entity.type}</text>{visible.map((edge, i) => { const a = (i / Math.max(visible.length, 1)) * Math.PI * 2 - Math.PI / 2; const x = 320 + Math.cos(a) * 210, y = 100 + Math.sin(a) * 68; return <g key={edge.id}><line x1="320" y1="100" x2={x} y2={y} stroke="hsl(var(--secondary))" strokeWidth="2" /><circle cx={x} cy={y} r="27" fill="hsl(var(--card))" stroke="hsl(var(--border))" /><text x={x} y={y + 4} textAnchor="middle" fill="hsl(var(--foreground))" fontSize="9">{(edge.entity?.name || "Missing").slice(0, 11)}</text></g>; })}</svg></div>; }
export function Pager({ page, total, limit, onPage }: { page: number; total: number; limit: number; onPage: (n: number) => void }) { const hasNext = page * limit < total; return <div className="flex justify-between items-center text-sm text-muted-foreground" aria-label="Pagination"><span>Page {page} · {total} records</span><div className="flex gap-2"><Button variant="outline" size="sm" aria-label="Previous page" disabled={page === 1} onClick={() => onPage(page - 1)}>Previous</Button><Button variant="outline" size="sm" aria-label="Next page" disabled={!hasNext} onClick={() => onPage(page + 1)}>Next</Button></div></div>; }