import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Check, ClipboardCheck, Edit3, RefreshCw, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { useToast } from "@/hooks/use-toast";

type Proposal = { id: number; panditId: number; status: string; confidence: number | string; source: string; reason: string; before: Record<string, unknown>; proposed: Record<string, unknown> };
type Location = { id: number; name: string; isActive: boolean; cities: Array<{ id: number; name: string; isActive: boolean }> };
type Queue = { items: Proposal[]; summary: Record<string, number> };
type AuditReport = { dryRun: boolean; batchId?: string | null; summary?: Record<string, number>; results?: Array<{ panditId: number; status?: string; issueCategories?: string[]; reason?: string; before?: Record<string, unknown>; proposed?: Record<string, unknown> }>; visibility?: { before?: Record<string, number>; after?: Record<string, number> } };
type ResolveReport = { batchId: string; published: Array<{ panditId: number; reasons: string[] }>; review: Array<{ panditId: number; reasons: string[] }>; blocked: Array<{ panditId: number; reasons: string[] }> };
type Editorial = { entityType: string; entityKey: string; status: "draft" | "reviewed" | "published"; introduction?: string; faqs?: unknown[] };

const safe = (value: unknown) => value == null || value === "" ? "Not recorded" : String(value);

export default function PanditLocationRectification() {
  const token = typeof window !== "undefined" ? localStorage.getItem("adminToken") || "" : "";
  const { toast } = useToast();
  const client = useQueryClient();
  const [reason, setReason] = useState("");
  const [auditReport, setAuditReport] = useState<AuditReport | null>(null);
  const [resolveReport, setResolveReport] = useState<ResolveReport | null>(null);
  const [edit, setEdit] = useState<Proposal | null>(null);
  const [editState, setEditState] = useState("");
  const [editCity, setEditCity] = useState("");
  const fetcher = async (url: string, options: RequestInit = {}) => {
    const response = await fetch(url, { ...options, credentials: "include", headers: { "Content-Type": "application/json", "x-admin-token": token, ...(options.headers || {}) } });
    const body = await response.json().catch(() => ({}));
    if (!response.ok) throw new Error(body.message || "Request failed");
    return body;
  };
  const queue = useQuery<Queue>({ queryKey: ["/api/admin/pandit-location-rectification"], queryFn: () => fetcher("/api/admin/pandit-location-rectification?limit=100") });
  const locations = useQuery<Location[]>({ queryKey: ["/api/admin/locations"], queryFn: () => fetcher("/api/admin/locations") });
  const editorials = useQuery<Editorial[]>({ queryKey: ["/api/admin/pandit-seo-editorial"], queryFn: () => fetcher("/api/admin/pandit-seo-editorial") });
  const audit = useMutation<AuditReport, Error, boolean>({ mutationFn: (persist) => fetcher("/api/admin/pandit-location-rectification/audit", { method: "POST", body: JSON.stringify({ persist, ...(persist ? { confirmed: true } : {}) }) }), onSuccess: (data) => { setAuditReport(data); client.invalidateQueries({ queryKey: ["/api/admin/pandit-location-rectification"] }); toast({ title: data.dryRun ? "Dry-run audit complete" : "Audit persisted", description: "The report contains no private contact data." }); }, onError: (error: Error) => toast({ title: "Audit failed", description: error.message, variant: "destructive" }) });
  const action = useMutation({ mutationFn: ({ id, kind }: { id: number; kind: "approve" | "reject" }) => fetcher(`/api/admin/pandit-location-rectification/${id}/${kind}`, { method: "POST", body: JSON.stringify({ confirmed: true, reason: reason.trim() }) }), onSuccess: () => { setReason(""); client.invalidateQueries({ queryKey: ["/api/admin/pandit-location-rectification"] }); toast({ title: "Review recorded" }); }, onError: (error: Error) => toast({ title: "Review failed", description: error.message, variant: "destructive" }) });
  const apply = useMutation({ mutationFn: (ids: number[]) => fetcher("/api/admin/pandit-location-rectification/apply", { method: "POST", body: JSON.stringify({ proposalIds: ids, confirmed: true, reason: reason.trim() }) }), onSuccess: () => { setReason(""); client.invalidateQueries({ queryKey: ["/api/admin/pandit-location-rectification"] }); toast({ title: "High-confidence proposals applied" }); }, onError: (error: Error) => toast({ title: "Apply failed", description: error.message, variant: "destructive" }) });
  const resolve = useMutation<ResolveReport, Error>({ mutationFn: () => fetcher("/api/admin/pandit-resolve-validate-publish", { method: "POST", body: JSON.stringify({ confirmed: true }) }), onSuccess: (data) => { setResolveReport(data); client.invalidateQueries({ queryKey: ["/api/admin/pandit-location-rectification"] }); setAuditReport(null); toast({ title: "Resolve, validate & publish complete", description: `${data.published.length} published · ${data.review.length} review · ${data.blocked.length} blocked` }); }, onError: (error: Error) => toast({ title: "Resolve, validate & publish failed", description: error.message, variant: "destructive" }) });
  const editMutation = useMutation({ mutationFn: ({ id, stateId, cityId }: { id: number; stateId: number; cityId: number }) => fetcher(`/api/admin/pandit-location-rectification/${id}`, { method: "PATCH", body: JSON.stringify({ stateId, cityId, confirmed: true, reason: reason.trim() }) }), onSuccess: () => { setEdit(null); setReason(""); client.invalidateQueries({ queryKey: ["/api/admin/pandit-location-rectification"] }); toast({ title: "Proposal updated" }); }, onError: (error: Error) => toast({ title: "Edit failed", description: error.message, variant: "destructive" }) });
  const pending = queue.data?.items.filter(item => item.status === "pending") || [];
  const highConfidence = pending.filter(item => Number(item.confidence) >= 0.9);
  const cities = useMemo(() => locations.data?.find(item => String(item.id) === editState)?.cities.filter(city => city.isActive) || [], [locations.data, editState]);
  const runPersisted = () => { if (!window.confirm("Persist this audit report and create review proposals? This is an auditable write.")) return; audit.mutate(true); };
  const requireReason = () => { if (!reason.trim()) { toast({ title: "Reason required", description: "Add an internal reason before applying or reviewing a proposal.", variant: "destructive" }); return false; } return true; };
  const reviewEditorial = async (item: Editorial, status: Editorial["status"]) => {
    try {
      await fetcher(`/api/admin/pandit-seo-editorial/${encodeURIComponent(item.entityType)}/${encodeURIComponent(item.entityKey)}/status`, { method: "PATCH", body: JSON.stringify({ status }) });
      await editorials.refetch();
      toast({ title: `Editorial marked ${status}` });
    } catch (error) { toast({ title: "Editorial update failed", description: error instanceof Error ? error.message : "Request failed", variant: "destructive" }); }
  };

  return <section className="space-y-4" aria-labelledby="location-rectification-heading">
     <Card><CardHeader className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><CardTitle id="location-rectification-heading" className="flex items-center gap-2 text-xl"><ClipboardCheck className="h-5 w-5 text-primary" /> Location rectification review</CardTitle><p className="mt-1 text-sm text-muted-foreground">Resolve canonical state and city evidence without exposing private contact details.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" disabled={audit.isPending || resolve.isPending} onClick={() => audit.mutate(false)}><RefreshCw className="mr-2 h-4 w-4" />Dry-run audit</Button><Button disabled={audit.isPending || resolve.isPending} onClick={runPersisted}>Persist audit</Button><Button variant="secondary" disabled={resolve.isPending} onClick={() => { if (window.confirm("Resolve deterministic locations, validate authoritative gates, and publish only records with no review items?")) resolve.mutate(); }}>Resolve, Validate &amp; Publish</Button></div></CardHeader><CardContent>
       {auditReport && <div className="mb-4 rounded-md border border-amber-300 bg-amber-50 p-3 text-sm text-amber-900"><strong>{auditReport.dryRun ? "Read-only report" : "Persisted report"}</strong> · {auditReport.batchId || "Audit completed"}<div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-4">{Object.entries(auditReport.summary || {}).map(([key, value]) => <div key={key} className="rounded border border-amber-200 bg-amber-100/60 p-2"><strong className="block">{value}</strong><span className="text-xs capitalize">{key}</span></div>)}</div>{auditReport.visibility && <div className="mt-3 overflow-x-auto"><table className="w-full min-w-[420px] text-xs"><caption className="mb-1 text-left font-semibold">Discovery visibility totals from audit</caption><thead><tr><th className="p-1 text-left">Metric</th><th className="p-1 text-right">Before</th><th className="p-1 text-right">After</th></tr></thead><tbody>{Array.from(new Set([...Object.keys(auditReport.visibility.before || {}), ...Object.keys(auditReport.visibility.after || {})])).map(key => <tr key={key} className="border-t border-amber-200"><td className="p-1">{key}</td><td className="p-1 text-right">{auditReport.visibility?.before?.[key] ?? "—"}</td><td className="p-1 text-right">{auditReport.visibility?.after?.[key] ?? "—"}</td></tr>)}</tbody></table></div>}</div>}
       {resolveReport && <div className="mb-4 rounded-md border border-primary/30 bg-primary/5 p-3 text-sm"><strong>Resolve, Validate &amp; Publish report</strong> · {resolveReport.batchId}<div className="mt-3 grid gap-4 md:grid-cols-3">{(["published", "review", "blocked"] as const).map(group => <div key={group} className="rounded border bg-background p-2"><h3 className="font-semibold capitalize">{group} ({resolveReport[group].length})</h3>{resolveReport[group].length ? <ul className="mt-2 space-y-1 text-xs">{resolveReport[group].map(item => <li key={item.panditId}><strong>Pandit #{item.panditId}</strong><span className="ml-1 text-muted-foreground">{item.reasons.length ? item.reasons.join(", ") : "All authoritative gates passed"}</span></li>)}</ul> : <p className="mt-2 text-xs text-muted-foreground">None</p>}</div>)}</div></div>}
      {auditReport?.results?.length ? <div className="mb-4 overflow-x-auto rounded-md border"><table className="w-full min-w-[760px] text-xs"><caption className="sr-only">One row per audited Pandit</caption><thead className="bg-muted/40 text-left text-muted-foreground"><tr><th className="p-2">Record</th><th className="p-2">Status</th><th className="p-2">Issue / reason</th><th className="p-2">Before</th><th className="p-2">Proposed after</th></tr></thead><tbody>{auditReport.results.map(row => <tr key={row.panditId} className="border-t align-top"><td className="p-2 font-medium">Pandit #{row.panditId}</td><td className="p-2">{row.status || "needs review"}</td><td className="p-2">{row.issueCategories?.join(", ") || row.reason || "No issue recorded"}</td><td className="p-2">{safe(row.before?.state)} / {safe(row.before?.city)}</td><td className="p-2">{row.proposed ? `${safe(row.proposed.state)} / ${safe(row.proposed.city)}` : "No correction proposed"}</td></tr>)}</tbody></table></div> : null}
      {editorials.data?.filter(item => item.entityType === "city" || item.entityType === "state").length ? <div className="mb-4 rounded-md border bg-muted/10 p-3"><h3 className="font-semibold text-primary">Location SEO editorial review</h3><p className="mt-1 text-xs text-muted-foreground">Persisted copy only. Publishing remains a reviewed, explicit action; no runtime AI copy is generated here.</p><div className="mt-3 space-y-2">{editorials.data.filter(item => item.entityType === "city" || item.entityType === "state").map(item => <div key={`${item.entityType}:${item.entityKey}`} className="flex flex-col gap-2 rounded border bg-background p-2 sm:flex-row sm:items-center sm:justify-between"><span className="text-sm">{item.entityType}:{item.entityKey} · <strong>{item.status}</strong></span><div className="flex gap-2"><Button size="sm" variant="outline" disabled={item.status === "draft"} onClick={() => reviewEditorial(item, "draft")}>Draft</Button>{item.status === "draft" && <Button size="sm" variant="outline" onClick={() => reviewEditorial(item, "reviewed")}>Mark reviewed</Button>}{item.status === "reviewed" && <Button size="sm" onClick={() => reviewEditorial(item, "published")}>Publish</Button>}</div></div>)}</div></div> : null}
      {queue.isLoading ? <p className="py-8 text-center text-sm text-muted-foreground">Loading rectification queue…</p> : queue.isError ? <div role="alert" className="flex items-center justify-between gap-3 py-6 text-sm text-destructive">Could not load the review queue.<Button size="sm" variant="outline" onClick={() => queue.refetch()}>Try again</Button></div> : !queue.data?.items.length ? <p className="py-8 text-center text-sm text-muted-foreground">No location proposals are waiting for review.</p> : <><div className="mb-4 grid grid-cols-2 gap-2 sm:grid-cols-4">{Object.entries(queue.data.summary).map(([key, value]) => <div key={key} className="rounded-md border bg-muted/20 p-3"><strong className="block text-lg text-primary">{value}</strong><span className="text-xs capitalize text-muted-foreground">{key}</span></div>)}</div><div className="mb-4 flex flex-col gap-3 rounded-md border bg-muted/10 p-3"><Label htmlFor="rectification-reason">Review reason (required for actions)</Label><Textarea id="rectification-reason" value={reason} onChange={event => setReason(event.target.value)} placeholder="Explain the evidence or decision for this batch" rows={2} /><Button className="w-fit" disabled={!highConfidence.length || apply.isPending} onClick={() => { if (requireReason() && window.confirm(`Apply ${highConfidence.length} high-confidence proposal(s)?`)) apply.mutate(highConfidence.map(item => item.id)); }}>Apply {highConfidence.length} high-confidence</Button></div><div className="space-y-3">{pending.map(item => <ProposalCard key={item.id} item={item} onApprove={() => requireReason() && action.mutate({ id: item.id, kind: "approve" })} onReject={() => requireReason() && action.mutate({ id: item.id, kind: "reject" })} onEdit={() => { setEdit(item); setEditState(safe(item.proposed.stateId)); setEditCity(safe(item.proposed.cityId)); }} busy={action.isPending} />)}</div></>}
    </CardContent></Card>
    <Dialog open={!!edit} onOpenChange={open => !open && setEdit(null)}><DialogContent><DialogHeader><DialogTitle>Edit canonical location</DialogTitle></DialogHeader><div className="space-y-4"><p className="text-sm text-muted-foreground">Only active catalogue locations can be selected. Pandit identity and contact data remain hidden.</p><div><Label htmlFor="rectification-state">State</Label><select id="rectification-state" className="mt-1 h-10 w-full rounded-md border bg-background px-3" value={editState} onChange={event => { setEditState(event.target.value); setEditCity(""); }}><option value="">Choose state</option>{locations.data?.filter(item => item.isActive).map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div><div><Label htmlFor="rectification-city">City</Label><select id="rectification-city" className="mt-1 h-10 w-full rounded-md border bg-background px-3" value={editCity} onChange={event => setEditCity(event.target.value)} disabled={!editState}><option value="">Choose city</option>{cities.map(city => <option key={city.id} value={city.id}>{city.name}</option>)}</select></div></div><DialogFooter><Button variant="outline" onClick={() => setEdit(null)}>Cancel</Button><Button disabled={!edit || !editState || !editCity || editMutation.isPending} onClick={() => { if (requireReason()) editMutation.mutate({ id: edit!.id, stateId: Number(editState), cityId: Number(editCity) }); }}>Save proposal</Button></DialogFooter></DialogContent></Dialog>
  </section>;
}

function ProposalCard({ item, onApprove, onReject, onEdit, busy }: { item: Proposal; onApprove: () => void; onReject: () => void; onEdit: () => void; busy: boolean }) {
  return <article className="rounded-lg border bg-background p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs text-muted-foreground">Proposal #{item.id} · record reference {item.panditId}</p><h3 className="mt-1 font-semibold text-primary">{safe(item.before.state)} / {safe(item.before.city)} <span aria-hidden="true">→</span> {safe(item.proposed.state)} / {safe(item.proposed.city)}</h3><div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-xs text-muted-foreground"><span>Confidence: <strong>{(Number(item.confidence) * 100).toFixed(0)}%</strong></span><span>Source: <strong>{safe(item.source)}</strong></span><span>Reason: {safe(item.reason)}</span></div></div><div className="flex shrink-0 flex-wrap gap-2"><Button size="sm" variant="outline" disabled={busy} onClick={onEdit}><Edit3 className="mr-1 h-4 w-4" />Edit</Button><Button size="sm" variant="outline" disabled={busy} onClick={onReject}><X className="mr-1 h-4 w-4" />Reject</Button><Button size="sm" disabled={busy} onClick={onApprove}><Check className="mr-1 h-4 w-4" />Approve</Button></div></div></article>;
}